apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
  annotations:
  {{ toYaml .Values.annotations | indent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "cronjob.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "cronjob.labels" . | nindent 12 }}
        spec:
        {{- if .Values.securityContext }}
          {{- if .Values.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- if .Values.securityContext.runAsGroup }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            {{- end }}
            {{- if .Values.securityContext.fsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          {{- if .Values.image.imagePullSecret }}
          imagePullSecrets:
          - name: {{ .Values.image.imagePullSecret }}
          {{- end }}
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            name: {{ .Chart.Name }}
            {{- with .Values.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- if .Values.command }}
            command: {{ .Values.command }}
            {{- end }}
            {{- with .Values.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with .Values.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
