# Default values for cronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: busybox
  tag: latest
  imagePullPolicy: Always
  imagePullSecret: ""

schedule: "*/15 * * * *"
command: ["/bin/sh"]
args:
  - "-c"
  - "echo $(date)"
env: []

resources: {}
#  limits:
#    cpu: 100m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

securityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 2000

annotations: {}
startingDeadlineSeconds: 240
failedJobsHistoryLimit: 5
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never
nodeSelector: {}
tolerations: []
affinity: {}
