apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "ghcr-auth.fullname" . }}
  labels:
    {{- include "ghcr-auth.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ printf `{"auths":{"ghcr.io":{"auth":"%s"}}}` (printf "%s:%s" .Values.github.userName .Values.github.token | b64enc) | b64enc | quote }}
