apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ genPrivateKey "rsa" | b64enc | quote }}